export enum LaunchActionTypes {
    SET_LAUNCHES = 'SET_LAUNCHES',
    FILTER_LAUNCHES = 'FILTER_LAUNCHES',
    SEARCH_LAUNCHES = 'SEARCH_LAUNCHES',
    RESET_SEARCH = 'RESET_SEARCH',
    ADD_FAVORITE = 'ADD_FAVORITE',
    REMOVE_FAVORITE = 'REMOVE_FAVORITE',
    SET_LAUNCHES_REQUEST = "SET_LAUNCHES_REQUEST",
    SET_LAUNCHES_SUCCESS = 'SET_LAUNCHES_SUCCESS',
    SET_LAUNCHES_FAILURE = 'SET_LAUNCHES_FAILURE'
  }